services:
    # PostgreSQL Database
    db:
        profiles: ["", "db-only"]
        image: postgres:16-alpine3.22
        restart: ${RESTART_POLICY:-no}
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - ./db-data:/var/lib/postgresql/data
        healthcheck:
            test: "pg_isready -U postgres"
            start_period: 4s # wait 4s to let db get ready for accepting connections
            start_interval: 2s # start first healthcheck after 2s

    backend:
        profiles: ["", "backend-only"]
        build:
            context: ./apps/backend
        environment:
            BACKEND_PORT: ${BACKEND_PORT}

            DB_HOST: db
            DB_PORT: 5432
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}

            BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
            BETTER_AUTH_URL: ${BETTER_AUTH_URL}

            LANGFLOW_BASE_URL: ${LANGFLOW_BASE_URL}
            LANGFLOW_API_KEY: ${LANGFLOW_API_KEY}

            TRUSTED_ORIGINS: ${TRUSTED_ORIGINS}
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}

    frontend:
        profiles: ["", "frontend-only"]
        build:
            context: ./apps/frontend
        environment:
            NODE_ENV: production
        ports:
            - ${FRONTEND_PORT:-3000}:3000
