name: Code Quality Checks Backend

on:
    push:
        branches:
            - main
            - develop
    pull_request:
    workflow_dispatch:

env:
    node_version: ${{ vars.NODE_VERSION_BACKEND }}
    working_directory: apps/backend

jobs:
    linting:
        name: Lint Backend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: Setup Backend
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}
                  working-directory: ${{ env.working_directory }}

            - name: Run License Check
              run: npm run license-check
              working-directory: ${{ env.working_directory }}

            - name: Lint Files
              run: npm run lint
              working-directory: ${{ env.working_directory }}

    check-client-generation:
        name: Verify Client Generation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Setup Backend
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}
                  working-directory: ${{ env.working_directory }}

            - name: Run Client Generation
              run: npm run generate:client
              working-directory: ${{ env.working_directory }}

            - name: Verify Client Is Up to Date
              run: |
                  if [[ -n "$(git status --porcelain)" ]]; then
                    echo "Client is not up to date. Please run 'npm run generate:client' in Backend and commit the changes."
                    echo "Uncommitted changes to client:"
                    git --no-pager diff
                    exit 1
                  else
                    echo "Client is up to date."
                  fi
