name: Code Quality Checks Backend

on:
    push:
        branches:
            - main
            - develop
    pull_request:
    workflow_dispatch:

env:
    node_version: ${{ vars.NODE_VERSION_BACKEND }}
    working_directory: apps/backend

jobs:
    linting:
        name: Linting Backend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Setup Backend
              uses: ./.github/workflows/setup/
              with:
                  node_version: ${{ env.node_version }}
                  working-directory: ${{ env.working_directory }}

            - name: Run License Check
              run: npm run license-check
              working-directory: ${{ env.working_directory }}

            - name: Linting
              run: npm run lint
              working-directory: ${{ env.working_directory }}
